name: Lint PR

on:
  pull_request:
    branches: [main]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML
        run: npx --yes htmlhint index.html
